/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const SubtitleLazyRouteImport = createFileRoute('/subtitle')()
const MarkdownLazyRouteImport = createFileRoute('/markdown')()
const HtmlLazyRouteImport = createFileRoute('/html')()
const EpubLazyRouteImport = createFileRoute('/epub')()

const SubtitleLazyRoute = SubtitleLazyRouteImport.update({
  id: '/subtitle',
  path: '/subtitle',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/subtitle.lazy').then((d) => d.Route))
const MarkdownLazyRoute = MarkdownLazyRouteImport.update({
  id: '/markdown',
  path: '/markdown',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/markdown.lazy').then((d) => d.Route))
const HtmlLazyRoute = HtmlLazyRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/html.lazy').then((d) => d.Route))
const EpubLazyRoute = EpubLazyRouteImport.update({
  id: '/epub',
  path: '/epub',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/epub.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epub': typeof EpubLazyRoute
  '/html': typeof HtmlLazyRoute
  '/markdown': typeof MarkdownLazyRoute
  '/subtitle': typeof SubtitleLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epub': typeof EpubLazyRoute
  '/html': typeof HtmlLazyRoute
  '/markdown': typeof MarkdownLazyRoute
  '/subtitle': typeof SubtitleLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epub': typeof EpubLazyRoute
  '/html': typeof HtmlLazyRoute
  '/markdown': typeof MarkdownLazyRoute
  '/subtitle': typeof SubtitleLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/epub' | '/html' | '/markdown' | '/subtitle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/epub' | '/html' | '/markdown' | '/subtitle'
  id: '__root__' | '/' | '/epub' | '/html' | '/markdown' | '/subtitle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpubLazyRoute: typeof EpubLazyRoute
  HtmlLazyRoute: typeof HtmlLazyRoute
  MarkdownLazyRoute: typeof MarkdownLazyRoute
  SubtitleLazyRoute: typeof SubtitleLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subtitle': {
      id: '/subtitle'
      path: '/subtitle'
      fullPath: '/subtitle'
      preLoaderRoute: typeof SubtitleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown': {
      id: '/markdown'
      path: '/markdown'
      fullPath: '/markdown'
      preLoaderRoute: typeof MarkdownLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html': {
      id: '/html'
      path: '/html'
      fullPath: '/html'
      preLoaderRoute: typeof HtmlLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epub': {
      id: '/epub'
      path: '/epub'
      fullPath: '/epub'
      preLoaderRoute: typeof EpubLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpubLazyRoute: EpubLazyRoute,
  HtmlLazyRoute: HtmlLazyRoute,
  MarkdownLazyRoute: MarkdownLazyRoute,
  SubtitleLazyRoute: SubtitleLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
